Repository hi-min-study/daliy-algorithm-study, pull requests merged in 2024-03, with the labels that each got.

#244 [20240301] BAJ/실버5/단어 정렬/구범모
  BeommoKoo-dev/202403/01 BAJ 1181 단어 정렬.md
Labels: 정렬

#240 [20240229] PRG / LV3 / 다단계 칫솔 판매 / 조재현
  HandamdeCloud/202402/29 PRG 다단계 칫솔 판매.md
Labels: 프로그래머스, 재귀

#237 [20240228] PRG / lv3 / 야근 지수 / 박이슬
  Yiseull/202402/28 PRG 야근 지수.md
Labels: 프로그래머스, Heap

#242 [20240229] BAJ / 골드5 / 센서 / 신예진
  born-A/202402/29 BAJ 센서.md
Labels: 그리디, 백준

#249 [20240304] PRG / lv2 / 행렬 테두리 회전하기 / 강병곤
  Curry4182/202403/4 행렬 테두리 회전하기.md
Labels: 구현, 프로그래머스

#248 [20240304] BAJ/골드5/피자 굽기/구범모
  BeommoKoo-dev/202403/04 1756 피자 굽기.md
Labels: 구현, 백준

#247 [20240304] PRG / lv3 / 최고의 집합 / 박이슬
  Yiseull/202403/04 PRG 최고의 집합.md
  Yiseull/202403/05 PRG 숫자 게임.md
Labels: 그리디, 프로그래머스

#246 [20240304] BAJ / 실버5 / 셀프 넘버 / 신예진
  born-A/202403/04 BAJ 셀프 넘버.md
Labels: 구현, 백준

#253 [20240305] PRG / lv2 / 수식 최대화 / 강병곤
  Curry4182/202403/5 수식 최대화.md
Labels: 프로그래머스, Stack

#251 [20240305] PRG / lv3 / 기지국 설치 / 박이슬
  Yiseull/202403/05 PRG 기지국 설치.md
Labels: 프로그래머스

#245 [20240305] PRG / LV3 / 두 큐 합 같게 만들기,양과 늑대, 가장 먼 노드, 퍼즐 조각 채우기 / 조재현
  HandamdeCloud/202403/04 PRG 가장 먼 노드.md
  HandamdeCloud/202403/04 PRG 두 큐 합 같게 만들기.md
  HandamdeCloud/202403/04 PRG 양과 늑대.md
  HandamdeCloud/202403/05 PRG 퍼즐 조각 채우기.md
Labels: DFS, 프로그래머스, Queue

#252 [20240305] BAJ / 실버5 / 직사각형 네개의 합집합의 면적 구하기 / 신예진
  born-A/202403/05 BAJ 직사각형 네개의 합집합의 면적 구하기.md
Labels: 구현, 백준

#258 [20240306] PRG / lv3 / 섬 연결하기 / 강병곤
  Curry4182/202403/06 섬 연결하기.md
Labels: 그리디, 프로그래머스, MST

#255 [20240306] BAJ/골드1/구간 합 구하기/구범모
  BeommoKoo-dev/202403/06 2042 구간 합 구하기.md
Labels: 백준, 누적합, Segment Tree

#254 [20240306] PRG / LV3 / 입국 심사,거스름돈 / 조재현
  HandamdeCloud/202403/06 PRG 거스름돈.md
  HandamdeCloud/202403/06 PRG 입굼 심사.md
Labels: DP, 프로그래머스, 투포인터

#257 [20240306] PRG / lv3 / 베스트앨범 / 박이슬
  Yiseull/202403/06 PRG 베스트앨범.md
Labels: 프로그래머스, Hash

#256 [20240306] BAJ / 실버5 / 막대기 / 신예진
  born-A/202403/06 BAJ 막대기.md
Labels: 구현, 백준

#262 [20240307] PRG / lv3 / 불량 사용자 / 박이슬
  Yiseull/202403/07 PRG 불량 사용자.md
Labels: 브루트포스, 프로그래머스

#260 [20240307] PRG / LV3 / 길 찾기 게임, 가장 긴 펠린드롬 / 조재현
  HandamdeCloud/202403/07 PRG 가장 긴 펠린드롬.md
  HandamdeCloud/202403/07 PRG 길 찾기 게임.md
Labels: 프로그래머스, 그래프, 문자열

#261 [20240307] BAJ / 실버1 / 영역 구하기 / 신예진
  born-A/202403/07 BAJ 영역 구하기.md
Labels: DFS, 백준

#263 [20240307] PRG / lv2 / 배달 / 강병곤
  Curry4182/202403/07 배달.md
Labels: 프로그래머스, 다익스트라

#268 [20240308] PRG / lv3 / [복습]징검다리 / 강병곤
  Curry4182/202403/08 징검다리.md
Labels: Binary search, 프로그래머스

#267 [20240308] PRG / lv3 / 징검다리 건너기 / 박이슬
  Yiseull/202403/08 PRG 징검다리 건너기.md
Labels: Binary search, 프로그래머스

#265 [20240308] BAJ/골드4/팀배분/구범모
  BeommoKoo-dev/202403/08 1953 팀배분.md
Labels: BFS, 백준

#266 [20240308] BAJ / 실버1 / 단지번호붙이기 / 신예진
  born-A/202403/08 BAJ 단지번호붙이기.md
Labels: DFS, 백준

#264 [20240308] PRG / LV3 / 경주로 건설 / 조재현
  HandamdeCloud/202403/08 PRG 경주로 건설.md
Labels: BFS, 프로그래머스

#270 [20240311] PRG / lv3 / 여행경로 / 박이슬
  Yiseull/202403/11 PRG 여행경로.md
Labels: DFS, 백트래킹, 프로그래머스

#272 [20240311] PRG / lv2 / 타겟넘버 / 신예진
  born-A/202403/11 PRG 네트워크.md
  born-A/202403/11 PRG 타겟 넘버.md
Labels: DFS, 프로그래머스

#273 [20240311] PRG / lv3 / 가장 먼 노드 / 강병곤
  Curry4182/202403/09 가장 먼 노드.md
Labels: DFS, 프로그래머스, 그래프

#277 [20240312] PRG / lv2 / [3차] 방금그곡 / 강병곤
  Curry4182/202403/12 [3차] 방금그곡.md
Labels: 구현, 프로그래머스

#269 [20240312] BAJ / 골드5 / 상어 초등학교 / 조재현
  HandamdeCloud/202403/11 PRG 호텔 방 배정.md
  HandamdeCloud/202403/12 BAJ 21608 상어 초등학교.md
Labels: 프로그래머스, 재귀

#274 [20240312] BAJ/골드3/백양로 브레이크/구범모
  BeommoKoo-dev/202403/12 11562 백양로 브레이크.md
Labels: 백준, 플로이드-워셜

#276 [20240312] PRG / lv3 / N으로 표현 / 신예진
  born-A/202403/12 PRG N으로 표현.md
Labels: DP, 프로그래머스

#275 [20240312] PRG / lv3 / 거스름돈 / 박이슬
  Yiseull/202403/12 PRG 거스름돈.md
  Yiseull/202403/13 PRG 부대복귀.md
Labels: DP, 프로그래머스

#279 [20240313] PRG / lv3 / 부대복귀 / 박이슬
  Yiseull/202403/13 PRG 부대복귀.md
Labels: 프로그래머스, 다익스트라

#278 [20240313] BAJ/실버5/수 정렬하기 2/구범모
  BeommoKoo-dev/202403/13 2751 수 정렬하기 2.md
Labels: 백준, 정렬

#280 [20240313] PRG / lv3 / 정수 삼각형 / 신예진
  born-A/202403/13. PRG 정수 삼각형.md
Labels: DP, 프로그래머스

#282 [20240313] PRG / lv3 / 여행경로 / 강병곤
  Curry4182/202403/13 여행경로.md
Labels: DFS, 프로그래머스

#285 [20240314] BAJ / lv3 / 특정한 최단 경로 / 박이슬
  Yiseull/202403/14 BAJ 특정한 최단 경로.md
Labels: 백준, 다익스트라

#281 [20240314] BAJ / 골드 3 / 괄호 추가하기 / 조재현
  HandamdeCloud/202403/13 BAJ 17281 ⚾.md
  HandamdeCloud/202403/17 166337 괄호 추가하기.md
Labels: DFS, 백준, 재귀

#283 [20240314] BAJ/실버2/폴짝폴짝/구범모
  BeommoKoo-dev/202403/14 1326 폴짝폴짝.md
Labels: BFS, 백준

#284 [20240314] PRG / lv3 / 등굣길 / 신예진
  born-A/202403/14 BAJ 등굣길.md
Labels: DP, 프로그래머스

#286 [20240314] PRG / lv2 / 테이블 해시 함수 / 강병곤
  Curry4182/202403/14 테이블 해시 함수.md
Labels: 구현, 프로그래머스

#287 [20240315] BAJ / 골드5 / 백도어 / 박이슬
  Yiseull/202403/15 BAJ 백도어.md
Labels: 백준, 다익스트라

#288 [20240315] BAJ/실버2/최대 곱/구범모
  BeommoKoo-dev/202403/15 1500 최대 곱.md
Labels: 백준, 수학

#289 [20240315] BAJ / 골드 5 / 파이프 옮기기 1 / 조재현
  HandamdeCloud/202403/18 17070 파이프 옮기기1.md
Labels: DP, 백준

#290 [20240315] BAJ / 골드5 / 토마토 / 신예진
  born-A/202403/15 BAJ 토마토.md
Labels: BFS

#291 [20240315] PRG / lv2 / 미로탈출 / 강병곤
  Curry4182/202403/15 미로탈출.md
Labels: BFS, 프로그래머스

#292 [20240318] BAJ/실버3/시리얼 번호/구범모
  BeommoKoo-dev/202403/18 1431 시리얼 번호.md
Labels: 백준, 정렬

#295 [20240318] BAJ / 실버3 / 퇴사 / 신예진
  born-A/202403/18 BAJ 퇴사.md
Labels: DP, 백준

#294 [20240318] PRG / lv2 / 양궁대회 / 박이슬
  Yiseull/202403/18 PRG 양궁대회.md
Labels: 구현, DFS, 프로그래머스

#296 [20240318] PRG / lv2 / 거리두기 확인하기 / 강병곤
  Curry4182/202403/18 거리두기 확인하기.md
Labels: 구현, 프로그래머스

#297 [20240319] BAJ/실버2/알고리즘 수업-너비우선탐색2/구범모
  BeommoKoo-dev/202403/19 24445 알고리즘 수업-너비우선탐색2.md
Labels: BFS, 백준

#293 [20240319] PRG / lv3 / 등굣길 / 조재현
  HandamdeCloud/202403/18 14890 경사로.md
  HandamdeCloud/202403/19 PRG 등굣길.md
Labels: 백준

#298 [20240319] BAJ / 실버4 / 빙고 / 신예진
  born-A/202403/19 BAJ 빙고.md
Labels: 구현, 백준

#299 [20240319] PRG / lv3 / 양과 늑대 / 박이슬
  Yiseull/202403/19 PRG 양과 늑대.md
Labels: DFS, 백트래킹, 프로그래머스

#300 [20240319] PRG / lv2 / 가장 큰 정사각형 찾기 / 강병곤
  Curry4182/202403/19 가장 큰 정사각형 찾기.md
Labels: DP, 프로그래머스

#301 [20240320] BAJ/실버3/풍선 터뜨리기/구범모
  BeommoKoo-dev/202403/20 2346 풍선 터뜨리기.md
Labels: 백준, Deque

#302 [20240320] PRG / lv3 / 부대복귀 / 조재현
  HandamdeCloud/202403/20 PRG 부대복귀.md
Labels: 프로그래머스, 다익스트라

#304 [20240320] PRG / lv3 / 파괴되지 않은 건물 / 박이슬
  Yiseull/202403/20 PRG 파괴되지 않은 건물.md
Labels: 구현, 프로그래머스, 누적합

#303 [20240320] BAJ / 실버5 / 기적의 매매법 / 신예진
  born-A/202403/20 BAJ 기적의 매매법.md
Labels: 구현, 백준

#305 [20240320] PRG / lv2 / 약수의 합 / 강병곤
  Curry4182/202403/20 약수의 합.md
Labels: 프로그래머스, 수학

#306 [20240321] BAJ / 브론즈 3 / 팰린드롬인지 확인하기 / 조재현
  HandamdeCloud/202403/21 BAJ 10988 팰린드롬인지 확인하기.md
Labels: 백준, 문자열

#307 [20240321] BAJ / 실버4 / 별 찍기 - 19 / 신예진
  born-A/202403/21 BAJ 별 찍기 - 19.md
Labels: 구현, 백준

#308 [20240321] BAJ/실버2/로또/구범모
  BeommoKoo-dev/202403/21 6603 로또.md
Labels: DFS, 백트래킹, 백준

#309 [20240321] PRG / lv2 / 과제 진행하기 / 박이슬
  Yiseull/202403/21 PRG 과제 진행하기.md
Labels: 구현, 프로그래머스

#310 [20240321] PRG / lv2 / 카펫 / 강병곤
  Curry4182/202403/21 카펫.md
Labels: 구현, 프로그래머스

#311 [20240322] PRG / lv2 / 무인도 여행 / 조재현
  HandamdeCloud/202403/22 PRG 무인도 여행.md
Labels: BFS, 프로그래머스

#314 [20240322] PRG / lv3 / 기둥과 보 설치 / 박이슬
  Yiseull/202403/22 PRG 기둥과 보 설치.md
Labels: 구현, 프로그래머스

#312 [20240322] BAJ/골드3/고속철도 설계하기/구범모
  BeommoKoo-dev/202403/22 1833 고속철도 설계하기.md
Labels: 백준, MST

#315 [20240322] PRG / lv2 / 리코쳇 로봇 / 강병곤
  Curry4182/202403/22 리코쳇 로봇.md
Labels: BFS, 프로그래머스

#313 [20240322] BAJ / 골드4 / 테트리스 게임 / 신예진
  born-A/202403/22 BAJ 테트리스 게임.md
Labels: 구현, 백준

#318 [20240325] BAJ / 실버4 / 설탕 배달 / 신예진
  born-A/202403/25 BAJ 설탕 배달.md
Labels: 구현, 백준

#316 [20240325] BAJ/골드2/아맞다우산/구범모
  BeommoKoo-dev/202403/25 17244 아맞다우산.md
Labels: BFS, 백준, 비트마스킹

#319 [20240325] PRG / lv2 / 시소 짝궁 / 조재현
  HandamdeCloud/202403/25 PRG 시소 짝궁.md
Labels: 구현, 프로그래머스

#317 [20240325] PRG / lv2 / 더 맵게 / 박이슬
  Yiseull/202403/25 PRG 더 맵게.md
Labels: 프로그래머스, Heap, 우선순위 큐

#320 [20240325] PRG / lv3 / 정수 삼각형 / 강병곤
  Curry4182/202403/22 리코쳇 로봇.md
  Curry4182/202403/25 정수 삼각형.md
Labels: DP

#323 [20240326] PRG / lv2 / [3차] n진수 게임 / 박이슬
  Yiseull/202403/26 PRG [3차] n진수 게임.md
Labels: 구현, 프로그래머스

#322 [20240326] PRG / lv2 / 최대값과 최소값 / 조재현
  HandamdeCloud/202403/26 PRG 최대값과 최소값.md
Labels: 구현, 프로그래머스

#321 [20240326] BAJ/골드2/철로/구범모
  BeommoKoo-dev/202403/26 13334 철로.md
Labels: 백준, 우선순위 큐, 정렬, 스위핑

#325 [20240326] PRG / lv2 / 프로세스 / 강병곤
  Curry4182/202403/26 프로세스.md
Labels: 브루트포스, Queue

#324 [20240326] BAJ / 실버4 / 할아버지는 유명해! / 신예진
  born-A/202403/26 BAJ 할아버지는 유명해!.md
Labels: 구현, 백준

#327 [20240327] BAJ/실버2/상자넣기/구범모
  BeommoKoo-dev/202403/27 1965 상자넣기.md
Labels: DP, 백준

#328 [20240327] BAJ / 실버2 / 트리의 부모 찾기 / 신예진
  born-A/202403/27 BAJ 트리의 부모 찾기.md
Labels: DFS, 백준

#326 [20240327] PRG / lv2 / 방문 길이 / 박이슬
  Yiseull/202403/27 PRG 방문 길이.md
Labels: 구현, 프로그래머스

#330 [20240328] PRG / lv2 / 2개 이하로 다른 비트 / 박이슬
  Yiseull/202403/28 PRG 2개 이하로 다른 비트.md
Labels: 구현, 프로그래머스

#329 [20240328] BAJ/골드5/개똥벌레/구범모
  BeommoKoo-dev/202403/28 3020 개똥벌레.md
Labels: 백준, 누적합

#331 [20240328] BAJ / 실버4 / ZOAC 3 / 신예진
  born-A/202403/28 BAJ ZOAC 3.md
Labels: 구현, 백준

#332 [20240328] PRG / lv3 / 최고의 집합 / 강병곤
  Curry4182/202403/27 광물캐기.md
  Curry4182/202403/28 최고의 집합.md
Labels: 프로그래머스, 수학

#335 [20240329] PRG / lv2 / 마법의 엘리베이터 / 박이슬
  Yiseull/202403/29 PRG 마법의 엘리베이터.md
Labels: 구현, 프로그래머스

#333 [20240329] BAJ / 실버3 / 회전하는 큐 / 신에진
  born-A/202403/29 BAJ 회전하는 큐.md
Labels: 백준, Queue

#334 [20240329] BAJ/실버2/안녕/구범모
  BeommoKoo-dev/202403/29 1535 안녕.md
Labels: DP
