Repository hi-min-study/daliy-algorithm-study, pull requests merged in 2024-02, with the labels that each got.

#156 [20240131] BAJ/골드3/Baaaaaaaaaduk2 (Easy)/구범모
  BeommoKoo-dev/202401/31 BAJ 16988 Baaaaaaaaaduk2 (Easy).md
  BeommoKoo-dev/202402/01 BAJ 2655 가장높은탑쌓기.md
Labels: DFS, BFS, 백준

#153 [20240131] BOJ / 골드4 / 무기공학 / 조재현
  HandamdeCloud/202401/31 BOJ 무기공학.md
Labels: DFS, 백트래킹, 백준

#154 [20240131] BAJ / 실버5 / 문서 검색 / 신예진
  born-A/202401/31 BAJ 문서 검색.md
Labels: 그리디, 백준

#155 [20240131] PRG / lv3 / 파괴되지 않은 건물 / 박이슬
  Yiseull/202401/31 PRG 파괴되지 않은 건물.md
Labels: 프로그래머스, 누적합

#157 [20240131] ST / level3 / 나무 조경 / 강병곤
  Curry4182/202401/31 나무 조경.md
  Curry4182/202401/Untitled.html
Labels: 재귀, Softeer

#158 [20240201] BOJ / 골드4 / 마법사 상어와 파이어볼 / 조재현
  HandamdeCloud/202402/01 BOJ 20056 마법사 상어와 파이어볼.md
Labels: 구현, 백준, 삼성SW Expert Academy

#159 [20240201] BAJ / 골드4 / 녹색 옷 입은 애가 젤다지? / 신예진
  born-A/202402/01 BAJ 녹색 옷 입은 애가 젤다지? .md
Labels: BFS, 백준

#160 [20240201] PRG / lv3 / 사라지는 발판 / 박이슬
  Yiseull/202402/01 PRG 사라지는 발판.md
Labels: 구현, 프로그래머스

#162 [20240202] BAJ/골드5/알약/구범모
  BeommoKoo-dev/202402/02 BAJ 4811 알약.md
Labels: DP, 백준

#163 [20240202] BOJ / 골드4 / 마법사 상어와 파이어볼 / 조재현
  HandamdeCloud/202402/02 BOJ 20056 마법사 상어와 파이어볼.md
Labels: 구현, 백준, 삼성SW Expert Academy

#164 [20240202] BAJ / 골드3 / 파티 / 신예진
  born-A/202402/02 BAJ 파티.md
Labels: BFS, 백준

#165 [20240202] BAJ / Gold1 / 외판원 순회 / 강병곤
  Curry4182/202402/02 외판원 순회.md
Labels: DP, 백준

#166 [20240202] PRG / lv2 / [PCCP 모의고사 1] 2번 / 박이슬
  Yiseull/202402/02 PRG [PCCP 모의고사 1] 2번.mc
Labels: 프로그래머스

#167 [20240205] BOJ / 실버1 / 효율적인 해킹 / 조재현
  HandamdeCloud/202402/05 BOJ 1325 효율적인 해킹.md
Labels: 백준, 그래프

#169 [20240205] BAJ / 실버4 / 걷기 / 신예진
  born-A/202402/05 BAJ 걷기.md
Labels: 그리디, 백준

#170 [20240205] PRG / lv2 / [PCCP 모의고사 1] 3번 / 박이슬
  Yiseull/202402/05 PRG [PCCP 모의고사 1] 3번.md
Labels: 프로그래머스

#174 [20240206] BAJ / 골드3 / 파티 / 신예진
  born-A/202402/06 BAJ 파티.md
Labels: 백준, 다익스트라

#172 [20240206] BAJ/골드3/벼룩시장/구범모
  BeommoKoo-dev/202402/06 BAJ 14943 벼룩시장.md
Labels: 그리디, 백준

#175 [20240206] PRG / lv3 / [PCCP 모의고사 1] 4번 / 박이슬
  Yiseull/202402/06 PRG [PCCP 모의고사 1] 4번.md
Labels: 프로그래머스, Heap

#176 [20240206] BAJ / Gold3 / 외판원 순회 3 / 강병곤
  Curry4182/202402/06 외판원 순회.md
Labels: DP, 백준, 재귀

#173 [20240206] PRG / Lv3 / 최고의 집합 / 조재현
  HandamdeCloud/202402/06 PRG 최고의 집합.md
  HandamdeCloud/202402/07 PRG 문자열 압축.md
Labels: 구현, 프로그래머스

#177 [20240207] BAJ / 실버1 / 영역 구하기 / 신예진
  born-A/202402/07 BAJ 영역 구하기.md
Labels: DFS, 백준

#178 [20240207] BAJ/골드5/도로의 개수/구범모
  BeommoKoo-dev/202402/07 BAJ 1577 도로의 개수.md
Labels: DP, 백준

#179 [20240207] BAJ / Gold2 / 청소년 상어 / 강병곤
  Curry4182/202402/07 청소년 상어.md
Labels: 구현, 백준

#180 [20240207] PRG / lv2 / 신입사원 교육 / 박이슬
  Yiseull/202402/07 PRG 신입사원 교육.md
Labels: 프로그래머스, Heap

#181 [20240208] BAJ / 골드5 / 호석이두마리치킨 / 조재현
  HandamdeCloud/202402/08 BAJ 21278 호석이 두마리 치킨.md
Labels: 그리디, 백준, 플로이드-워셜, 다익스트라

#182 [20240208] BAJ/골드2/퍼즐/구범모
  BeommoKoo-dev/202402/08 BAJ 1525 퍼즐.md
Labels: BFS, 백준

#183 [20240208] PRG / lv3 / 카페 확장 / 박이슬
  Yiseull/202402/08 PRG 카페 확장.md
Labels: 프로그래머스, Queue

#184 [20240208] BAJ / 실버2 / 체인 / 신예진
  born-A/202402/08 BAJ 체인.md
Labels: 그리디, 백준

#185 [20240208] BAJ / Gold5 / 수 고르기 / 강병곤
  Curry4182/202402/08 수 고르기.md
Labels: 백준, 투포인터

#186 [20240213] PRG / LV2 / 프렌즈4블록 / 조재현
  HandamdeCloud/202402/13 PRG 프랜즈4블록.md
Labels: 구현, 프로그래머스

#187 [20240213] BAJ/골드3/마라톤2/구범모
  BeommoKoo-dev/202402/13 BAJ 10653 마라톤2.md
Labels: DP, 백준

#188 [20240213] BAJ / 실버4 / Project Teams / 신예진
  born-A/202402/13 BAJ Projec Teams.md
Labels: 그리디, 백준

#189 [20240213] BAJ / 실버1 / 회전 초밥 / 박이슬
  Yiseull/202402/13 BAJ 회전 초밥.md
Labels: 브루트포스, 백준, 투포인터, 슬라이딩 윈도우

#190 [20240213] BAJ / Gold2 / 동전2 / 강병곤
  Curry4182/202402/13. 동전2.md
Labels: 백준, 재귀

#191 [20240214] PRG / LV2 / 방금그곡 / 조재현
  HandamdeCloud/202402/14 PRG 방금그곡.md
Labels: 구현, 프로그래머스, 문자열

#192 [20240214] BAJ/골드3/하늘에서 별똥별이 빗발친다/구범모
  BeommoKoo-dev/202402/14 BAJ 14658 하늘에서 별똥별이 빗발친다.md
Labels: 브루트포스, 백준

#194 [20240214] BAJ / 실버4 / 반복수열 / 신예진
  born-A/202402/14 BAJ 반복수열.md
Labels: DFS, 백준

#195 [20240214] BAJ / 실버1 / 쉬운 계단 수 / 강병곤
  Curry4182/202402/14 쉬운 계단 수.md
Labels: DP, 백준

#196 [20240215] PRG / LV2 / 양궁대회 / 조재현
  HandamdeCloud/202402/15 PRG 양궁대회.md
Labels: DFS, 프로그래머스

#197 [20240215] BAJ/골드5/강의실/구범모
  BeommoKoo-dev/202402/15 BAJ 1374 강의실.md
Labels: 그리디, 백준

#198 [20240215] PRG / lv2 / N개의 최소공배수 / 박이슬
  Yiseull/202402/15 PRG N개의 최소공배수.md
Labels: 프로그래머스

#199 [20240215] BAJ / 골드3 / 성곽 / 신예진
  born-A/202402/15 BAJ 성곽.md
Labels: BFS, 백준

#200 [20240215] BAJ / 실버2 / 제곱 수의 합 / 강병곤
  Curry4182/202402/15 제곱수의 합.md
Labels: DP, 백준

#202 [20240216] BAJ/골드4/리조트/구범모
  BeommoKoo-dev/202402/16 BAJ 13302 리조트.md
Labels: DP, 백준

#201 [20240216] BAJ / 실버2 / 초콜릿 식사 / 신예진
  born-A/202402/16 BAJ 초콜릿 식사.md
Labels: 그리디, 백준

#204 [20240216] BAJ / 골드4 / 사냥꾼 / 박이슬
  Yiseull/202402/16 BAJ 사냥꾼.md
Labels: Binary search, 백준

#207 [20240219] BAJ/골드5/세 친구/구범모
  BeommoKoo-dev/202402/19 BAJ 17089 세 친구.md
Labels: 브루트포스, 백준

#203 [20240216] BAJ / 실버3 / 퇴사 / 강병곤
  Curry4182/202402/.vs/202402/v17/.suo
  Curry4182/202402/.vs/VSWorkspaceState.json
  Curry4182/202402/.vs/slnx.sqlite
  Curry4182/202402/16 퇴사.md
  Curry4182/202402/17 합분해.md
Labels: DP, 백준

#206 [20240219] BAJ / 실버3 / 개으른 백곰 / 박이슬
  Yiseull/202402/19 BAJ 게으른 백곰.md
Labels: 백준, 슬라이딩 윈도우

#205 [20240219] PRG / LV2 / 괄호 변환 / 조재현
  HandamdeCloud/202402/19 PRG 괄호 변환.md
Labels: 구현, 프로그래머스, 재귀, Stack

#208 [20240219] BAJ / 골드2 / 퍼즐 / 신예진
  born-A/202402/19 BAJ 퍼즐.md
Labels: BFS, 백준

#213 [20240220] BAJ / 실버1 / 동물원 / 강병곤
  Curry4182/202402/20 동물원.md
Labels: DP, 백준

#212 [20240220] BAJ / 골드5 / 숨바꼭질 3 / 박이슬
  Yiseull/202402/20 BAJ 숨바꼭질 3.md
Labels: BFS, 백준

#209 [20240220] PRG / LV2 / 호텔 대실 / 조재현
  HandamdeCloud/202402/20 PRG 호텔 대실.md
  HandamdeCloud/202402/21 PRG 수식 최대화.md
Labels: 구현, 프로그래머스

#211 [20240220] BAJ / 골드2 / 퍼즐 / 신예진
  born-A/202402/20 BAJ 퍼즐.md
Labels: BFS, 백준

#210 [20240220] BAJ/골드2/레이스/구범모
  BeommoKoo-dev/202402/20 BAJ 1508 레이스.md
  BeommoKoo-dev/202402/21 BAJ 2073 수도배관공사.md
  BeommoKoo-dev/202402/22 BAJ 1749 점수따먹기.md
Labels: Binary search, 백준

#214 [20240221] PRG / lv2 / 순위 검색 / 박이슬
  Yiseull/202402/21 PRG 순위 검색.md
Labels: Binary search, 프로그래머스

#216 [20240221] BAJ / 골드4 / 지뢰찾기 / 신예진
  born-A/202402/21 BAJ 지뢰찾기.md
Labels: 그리디, 백준

#215 [20240221] BAJ / 골드4 / 가장 긴 증가하는 부분수열4 / 강병곤
  Curry4182/202402/21 가장 긴 증가하는 부분수열 4.md
Labels: DP, 백준

#219 [20240222] PRG / lv3 / 순위 / 박이슬
  Yiseull/202402/22 PRG 순위.md
Labels: 프로그래머스, 플로이드-워셜

#218 [20240222] BAJ / 실버1 / 경로 찾기 / 신예진
  born-A/202402/22  BAJ 경로 찾기.md
Labels: 백준, 플로이드-워셜

#224 [20240223] BAJ / 골드5 / 1 학년 / 강병곤
  Curry4182/202402/23 1학년.md
Labels: DP, 백준

#221 [20240223] BAJ/골드5/시간 관리/구범모
  BeommoKoo-dev/202402/23 BAJ 1263 시간 관리.md
Labels: 그리디, 백준

#217 [20240223] PRG / LV2 / 전력망을 둘로 나누기 / 조재현
  HandamdeCloud/202402/22 PRG 배달.md
  HandamdeCloud/202402/23 PRG 전력망을 둘로 나누기.md
Labels: 프로그래머스, 플로이드-워셜

#223 [20240223] BAJ / 골드5 / A와 B / 신예진
  born-A/202402/23 BAJ A와 B.md
Labels: 그리디, 백준

#222 [20240223] PRG / lv3 / 길 찾기 게임 / 박이슬
  Yiseull/202402/23 PRG 길 찾기 게임.md
Labels: 프로그래머스, 그래프, 재귀

#227 [20240226] BAJ/골드5/노드사이의 거리/구범모
  BeommoKoo-dev/202402/26 BAJ 1240 노드 사이의 거리.md
Labels: BFS, 백준

#228 [20240226] PRG / lv3 / 디스크 컨트롤러 / 박이슬
  Yiseull/202402/26 PRG 디스크 컨트롤러.md
Labels: 프로그래머스, Heap

#226 [20240226] BAJ / 실버3 / 달팽이 / 신예진
  born-A/202402/26 BAJ 달팽이.md
Labels: 그리디, 백준

#225 [20240226] PRG / LV3 / 셔틀 버스 / 조재현
  HandamdeCloud/202402/26 PRG 셔틀버스.md
Labels: 구현, 프로그래머스

#232 [20240227] PRG / lv2 / 괄호 변환 / 강병곤
  Curry4182/202402/27. 괄호 변환.md
Labels: 백준, 재귀

#233 [20240227] PRG / LV3 / 표 편집 / 조재현
  HandamdeCloud/202402/27 PRG 표 편집.md
Labels: 프로그래머스

#230 [20240227] BAJ/골드5/농장 관리/구범모
  BeommoKoo-dev/202402/27 BAJ 1245 농장 관리.md
  BeommoKoo-dev/202402/28 1051 가장 큰 정사각형.md
Labels: BFS, 백준

#231 [20240227] BAJ / 실버3 / 파일 정리 / 신예진
  born-A/202402/27 BAJ 파일 정리.md
Labels: 구현, 백준

#234 [20240227] PRG / lv4 / 호텔 방 배정 / 박이슬
  Yiseull/202402/27 PRG 호텔 방 배정.md
Labels: 프로그래머스

#239 [20240228] PRG / lv1 / 나머지가 1이 되는 수 찾기 / 강병곤
  Curry4182/202402/28 나머지가 1이 되는 수 찾기.md
Labels: 프로그래머스

#236 [20240228] PRG / LV3 / 다단계 칫솔 판매 / 조재현
  HandamdeCloud/202402/28 PRG 다단계 칫솔 판매.md
Labels: 프로그래머스, 재귀

#235 [20240228] BAJ/실버1/음식물 피하기/구범모
  BeommoKoo-dev/202402/28 1743 음식물 피하기.md
Labels: BFS, 백준

#238 [20240228] BAJ / 실버1 / 케빈 베이컨의 6단계 법칙 / 신예진
  born-A/202402/28 BAJ 케빈 베이컨의 6단계 법칙.md
Labels: 백준, 플로이드-워셜

#241 [20240229] BAJ/실버1/컴백홈/구범모
  BeommoKoo-dev/202402/29 BAJ 1189 컴백홈.md
Labels: DFS, 백준
